backend:
  name: git-gateway
  branch: master
media_folder: static/img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "aticle"
      name: "aticle"
      file: "content/aticle.md"
      fields: 
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'article'
          name: "article"
          widget: list
          fields: 
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - { label: "Publish Date", name: "date", widget: "datetime" }
            - { label: "Img", name: "img", widget: "string"}
            - { label: "Link", name: "link", widget: "string"}
